name: Generate Chart

on:
  push:
    paths:
      - 'data/**'

jobs:
  build-chart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install pandas matplotlib
    - run: python scripts/generate_chart.py
    - run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/chart.png
        git commit -m "Update chart" || echo "No changes"
        git push
