name: Generate Chart

on:
  push:
    paths:
      - 'data/**'

jobs:
  build-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # vajalik, et saada kogu ajalugu
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install pandas matplotlib
      - run: python scripts/generate_chart.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update chart"
          file_pattern: "docs/chart.png"
