name: Generate Chart

on:
  push:
    paths:
      - 'data/**'

jobs:
  build-chart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install pandas matplotlib
    - run: python scripts/generate_chart.py
    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git pull origin main
        git add docs/chart.png
        git commit -m "Update chart" || echo "No changes"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
